<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    private array $images = [
        'house'      => [
            'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
            'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
            'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800',
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
            'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800',
            'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=800',
        ],
        'apartment'  => [
            'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
            'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
            'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
            'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
            'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
        ],
        'land'       => [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
            'https://images.unsplash.com/photo-1473773508845-188df298d2d1?w=800',
            'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=800',
            'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=800',
            'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
        ],
        'studio'     => [
            'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800',
            'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
            'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
            'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
            'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
            'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800',
        ],
    ];

    public function run(): void
    {
        $carlos = User::where('email', 'prop@habitta.mx')->first();
        $maria  = User::where('email', 'maria@habitta.mx')->first();

        $properties = [
            [
                'user_id'         => $carlos->id,
                'title'           => 'Casa moderna con jardín en Colonia Polanco',
                'description'     => 'Hermosa casa moderna con acabados de lujo, amplio jardín privado y alberca. Ubicada en una de las zonas más exclusivas de la Ciudad de México, a solo minutos de restaurantes, centros comerciales y escuelas de primer nivel. Cuenta con 3 recámaras amplias, sala de estar, comedor, cocina integral y 2 cajones de estacionamiento techado.',
                'type'            => 'house',
                'listing_type'    => 'sale',
                'price'           => 4500000.00,
                'location'        => 'Horacio 1034, Polanco V Sección',
                'city'            => 'Ciudad de México',
                'state'           => 'CDMX',
                'area'            => 220.00,
                'bedrooms'        => 3,
                'bathrooms'       => 3,
                'floor'           => null,
                'year_built'      => 2020,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garage'      => true,
                'has_garden'      => true,
                'has_pool'        => true,
                'has_security'    => true,
                'views_count'     => 142,
            ],
            [
                'user_id'         => $carlos->id,
                'title'           => 'Departamento de lujo en Santa Fe',
                'description'     => 'Espectacular departamento en torre de lujo con vista panorámica a la ciudad. Cuenta con cocina integral equipada, sala-comedor amplio, balcón privado y acceso a amenidades exclusivas del edificio como gimnasio, área de yoga, rooftop con alberca y salón de eventos.',
                'type'            => 'apartment',
                'listing_type'    => 'rent',
                'price'           => 28000.00,
                'location'        => 'Blvd. Manuel Ávila Camacho 88, Santa Fe',
                'city'            => 'Ciudad de México',
                'state'           => 'CDMX',
                'area'            => 120.00,
                'bedrooms'        => 2,
                'bathrooms'       => 2,
                'floor'           => 15,
                'year_built'      => 2022,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garage'      => true,
                'has_garden'      => false,
                'has_pool'        => true,
                'has_security'    => true,
                'has_gym'         => true,
                'has_elevator'    => true,
                'views_count'     => 89,
            ],
            [
                'user_id'         => $carlos->id,
                'title'           => 'Terreno residencial en Monterrey Norte',
                'description'     => 'Terreno en zona residencial consolidada, ideal para construcción de casa propia o proyecto de inversión. Cuenta con todos los servicios disponibles en la calle: agua, luz, drenaje. Zona de rápido crecimiento con plusvalía ascendente.',
                'type'            => 'land',
                'listing_type'    => 'sale',
                'price'           => 950000.00,
                'location'        => 'Privada Las Cumbres, sector norte',
                'city'            => 'Monterrey',
                'state'           => 'Nuevo León',
                'area'            => 300.00,
                'bedrooms'        => null,
                'bathrooms'       => null,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'views_count'     => 55,
            ],
            [
                'user_id'         => $maria->id,
                'title'           => 'Casa colonial en el Centro Histórico de Guadalajara',
                'description'     => 'Majestuosa casa colonial completamente restaurada en el corazón del centro histórico. Techos altos, pisos de madera originales, patio central con fuente y jardín interior. Perfecta para vivir o desarrollar un proyecto de hotel boutique o espacio cultural.',
                'type'            => 'house',
                'listing_type'    => 'sale',
                'price'           => 3800000.00,
                'location'        => 'Av. Hidalgo 523, Centro Histórico',
                'city'            => 'Guadalajara',
                'state'           => 'Jalisco',
                'area'            => 380.00,
                'bedrooms'        => 5,
                'bathrooms'       => 4,
                'year_built'      => 1920,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garden'      => true,
                'has_security'    => true,
                'views_count'     => 201,
            ],
            [
                'user_id'         => $maria->id,
                'title'           => 'Estudio amueblado en Zona Rosa',
                'description'     => 'Moderno estudio completamente amueblado en la vibrante Zona Rosa. Ideal para profesionistas o estudiantes. Incluye sala-comedor integrado, cocina equipada, baño completo y área de trabajo. Edificio con seguridad 24/7 y ubicación inmejorable a pasos del metro.',
                'type'            => 'studio',
                'listing_type'    => 'rent',
                'price'           => 12500.00,
                'location'        => 'Liverpool 78, Zona Rosa',
                'city'            => 'Ciudad de México',
                'state'           => 'CDMX',
                'area'            => 38.00,
                'bedrooms'        => 1,
                'bathrooms'       => 1,
                'floor'           => 4,
                'year_built'      => 2019,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_security'    => true,
                'has_elevator'    => true,
                'views_count'     => 310,
            ],
            [
                'user_id'         => $maria->id,
                'title'           => 'Casa con alberca en Cuernavaca',
                'description'     => 'Amplia casa de un nivel con alberca desbordante y jardín tropical. Ambiente de descanso total en la Ciudad de la Eterna Primavera. Cuenta con sala de televisión, cocina de gas, cuarto de servicio y 2 cajones de estacionamiento. Fraccionamiento privado con vigilancia.',
                'type'            => 'house',
                'listing_type'    => 'rent',
                'price'           => 22000.00,
                'location'        => 'Fracc. Jardines de Cuernavaca, Av. Palmira',
                'city'            => 'Cuernavaca',
                'state'           => 'Morelos',
                'area'            => 180.00,
                'bedrooms'        => 3,
                'bathrooms'       => 2,
                'year_built'      => 2010,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garage'      => true,
                'has_garden'      => true,
                'has_pool'        => true,
                'has_security'    => true,
                'views_count'     => 178,
            ],
            [
                'user_id'         => $carlos->id,
                'title'           => 'Departamento frente al mar en Cancún',
                'description'     => 'Espectacular departamento con vista al mar Caribe desde el balcón. Ubicado en la Zona Hotelera de Cancún, a pasos de la playa. Amueblado con gusto, cocina integral, área de lavandería y estacionamiento subterráneo. Edificio con alberca, palapa y acceso directo a la playa.',
                'type'            => 'apartment',
                'listing_type'    => 'sale',
                'price'           => 6200000.00,
                'location'        => 'Blvd. Kukulcan Km 12.5, Zona Hotelera',
                'city'            => 'Cancún',
                'state'           => 'Quintana Roo',
                'area'            => 95.00,
                'bedrooms'        => 2,
                'bathrooms'       => 2,
                'floor'           => 8,
                'year_built'      => 2021,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garage'      => true,
                'has_pool'        => true,
                'has_security'    => true,
                'has_gym'         => true,
                'has_elevator'    => true,
                'views_count'     => 425,
            ],
            [
                'user_id'         => $maria->id,
                'title'           => 'Terreno comercial en Querétaro',
                'description'     => 'Terreno en zona de alto tráfico vehicular y peatonal, ideal para local comercial, oficinas o desarrollo mixto. Excelente conectividad con vías principales. Zona de alto crecimiento económico con incentivos fiscales para nuevas inversiones.',
                'type'            => 'land',
                'listing_type'    => 'sale',
                'price'           => 1800000.00,
                'location'        => 'Av. Constituyentes 200, El Marqués',
                'city'            => 'Querétaro',
                'state'           => 'Querétaro',
                'area'            => 500.00,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'views_count'     => 93,
            ],
            [
                'user_id'         => $carlos->id,
                'title'           => 'Casa en fraccionamiento privado en Mérida',
                'description'     => 'Casa nueva en moderno fraccionamiento privado al norte de Mérida. Diseño contemporáneo, techos altos, cocina abierta al área social. Fraccionamiento cuenta con amenidades: cancha de tenis, área de BBQ, parque infantil y vigilancia 24/7.',
                'type'            => 'house',
                'listing_type'    => 'sale',
                'price'           => 2750000.00,
                'location'        => 'Fracc. Altabrisa, calle 60 Norte',
                'city'            => 'Mérida',
                'state'           => 'Yucatán',
                'area'            => 165.00,
                'bedrooms'        => 3,
                'bathrooms'       => 2,
                'year_built'      => 2023,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garage'      => true,
                'has_garden'      => true,
                'has_security'    => true,
                'views_count'     => 166,
            ],
            [
                'user_id'         => $maria->id,
                'title'           => 'Penthouse con terraza en San Pedro Garza García',
                'description'     => 'Exclusivo penthouse de dos niveles con terraza privada de 80m² y vista panorámica a la Sierra Madre. Acabados de primer nivel, cocina de diseño, sala con doble altura, baño principal con tina y regadera italiana. Edificio de lujo con concierge 24hrs.',
                'type'            => 'apartment',
                'listing_type'    => 'sale',
                'price'           => 9500000.00,
                'location'        => 'Calzada del Valle 400 Ote., San Pedro Garza García',
                'city'            => 'San Pedro Garza García',
                'state'           => 'Nuevo León',
                'area'            => 280.00,
                'bedrooms'        => 4,
                'bathrooms'       => 4,
                'floor'           => 22,
                'year_built'      => 2024,
                'has_water'       => true,
                'has_electricity' => true,
                'has_drainage'    => true,
                'has_garage'      => true,
                'has_garden'      => false,
                'has_pool'        => true,
                'has_security'    => true,
                'has_gym'         => true,
                'has_elevator'    => true,
                'views_count'     => 540,
            ],
        ];

        foreach ($properties as $data) {
            $imageSet = $this->images[$data['type']] ?? $this->images['house'];

            unset($data['images']);
            $property = Property::create($data);

            foreach ($imageSet as $index => $imageUrl) {
                PropertyImage::create([
                    'property_id' => $property->id,
                    'path'        => $imageUrl,
                    'is_main'     => $index === 0,
                    'order'       => $index,
                ]);
            }
        }
    }
}
